language: java
sudo: false

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE database;" -U postgres
  - psql -c "CREATE DATABASE cars;" -U postgres
  - psql -c "CREATE DATABASE todolist;" -U postgres
  - psql -c "CREATE DATABASE musicplace;" -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ephemeralin@gmail.com
    on_success: always # default: change
    on_failure: always # default: always