--drop all tables
drop table role_sets;
drop table permissions;
drop table files;
drop table comments;
drop table tickets;
drop table categories;
drop table states;
drop table users;
drop table roles;
